### ISSUE TITLE
JDWP Transport dt_socket failed to initialize，Address already in use

### ISSUE THREAD

**Issue by wenbin151** [actframework/act-maven-plugin#8]
Error message:

```
ERROR: transport error 202: bind failed: Address already in use
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
```

Sub process returned with exit code: 2

Listening for transport dt_socket at address: 5005

Possible solution: use another port randomly when the JDWP port is use？

**Comment by greenlaw110** [comment]
@wenbin151 try use -Dact.jpdaPort=0 to specify a random JDWP port, or any other positive number less than 65535 and not 5005 to fix the conflict.
